URL_1=http://www.facebook.com
URL_2=http://www.google.com
driverProperty=webdriver.chrome.driver
driverPath=\\src\\test\\java\\com\\projectName\\drivers\\chromedriver.exe
ExcelSheetName=Sheet1
log4jPropertiesFileLoc=
chrome=chrome
fburltest=https://www.facebook.com/