url=https://www.flipkart.com/?
Atkinsurl=https://www.atkinsrealis.com/en/markets-and-services
browser=firefox
redifflogin=https://mail.rediff.com/cgi-bin/login.cgi
demoqa=https://demoqa.com/checkbox
edurekaurl=https://www.edureka.co/signin
fbdirectory=https://www.facebook.com/biz/directory/
fburl=https://www.facebook.com/
Gogleurl=http://www.google.com/