url=https://www.flipkart.com/?
Atkinsurl=https://www.atkinsrealis.com/en/sustainability
browser=firefox
redifflogin=https://mail.rediff.com/cgi-bin/login.cgi
demoqa=https://demoqa.com/checkbox
edurekaurl=https://www.edureka.co
fbdirectory=https://www.facebook.com/biz/directory/
fburl=https://www.facebook.com/
Gogleurl=http://www.google.com/
flipfashion=//div[contains(text(),'Fashion')]
flip=//span[@class='b3wTlE']
newaccount=//span[contains(text(),'Create new account')]