flipurl=https://www.flipkart.com/?
Atkinsurl=https://www.atkinsrealis.com/en/sustainability
browser=firefox
redifflogin=https://mail.rediff.com/cgi-bin/login.cgi
demoqa=https://demoqa.com/checkbox
edurekaurl=https://www.edureka.co
fbdirectory=https://www.facebook.com/biz/directory/
fburl=https://www.facebook.com/
Gogleurl=http://www.google.com/
flipfashion=//div[contains(text(),'Fashion')]
flip=//span[@class='b3wTlE']
newaccount=//span[contains(text(),'Create new account')]
forgotpass=//span[contains(text(),'Forgotten password')]/ancestor::div[1]
fbdirpath=//div[@class='_4-u2 _80gx _4-u8']//a
fbdirpath1=//div[@class='_80gt _2ph_']
googlefr=https://www.google.com/?hl=fr
expandtree=//span[@class='rc-tree-switcher rc-tree-switcher_close']
Homechbox=//span[@aria-label='Select Home']
